<section class="contact-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 contact-text">
					<h4>Napište nám</h4>
					<p>Nullam lacinia ex eleifend orci portt-itor, suscipit interdum augue condi-mentum. Etiam pretium turpis eget nibh laoreet iaculis. Vivamus auctor mi eget odio feugiat.</p>
					<div class="cont-info">
						<div class="ci-icon">
							<img src="img/icons/1.png" alt="">
						</div>
						<span>Žižkovo nám. 5, Olomouc</span>
					</div>
					<div class="cont-info">
						<div class="ci-icon">
							<img src="img/icons/2.png" alt="">
						</div>
						<span>	585 635 102 </span> <br>
                        <span>	Vlasta Gáborová, sekretářka katedry</span>
					</div>
					<div class="cont-info">
						<div class="ci-icon">
							<img src="img/icons/2.png" alt="">
						</div>
						<span>vlasta.gaborova@upol.cz</span>
					</div>
				</div>
				<div class="col-lg-9">
					<form class="contact-form">
						<div class="row">
							<div class="col-md-6">
								<input type="text" placeholder="Zadejte jméno">
							</div>
							<div class="col-md-6">
								<input type="text" placeholder="Zadejte svůj email">
							</div>
							<div class="col-md-12">
								<input type="text" placeholder="Předmět">
								<textarea placeholder="Napište nám"></textarea>
								<button class="site-btn">Poslat</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
		<div class="map" id="map-canvas"></div>
	</section>
