<!-- O projektu text-->
	<section class="about-section spad pt-0">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 about-text">
					<h3>Co děláme v projektu</h3>
					<p>Nullam lacinia ex eleifend orci porttitor, suscipit interdum augue condimentum. Etiam pretium turpis eget nibh laoreet iaculis. Vivamus auctor mi eget odio feugiat, quis aliquet velit ornare. Integer egestas sit amet neque sed elementum. Fusce ut turpis felis. Etiam pretium pharetra augue, ac porttitor dolor consequat eget. Cras tempor suscipit enim vehicula ultrices. Mauris sed orci blandit, rhoncus massa non, tincidunt odio. Ut ullamcorper lobortis hendrerit. </p>
				</div>
				<div class="col-lg-6">
					<img src="./img/about.jpg" alt="">
				</div>
			</div>
		</div>
	</section>
	<!-- O projektu text END -->


	<!-- Sčítání lidu -->
	<section class="milestones-section set-bg" data-setbg="img/milestones-bg.jpg">
		<div class="container">
			<div class="row milestones-top-text">
				<div class="col-lg-8">
					<p>Nullam lacinia ex eleifend orci porttitor, suscipit interdum augue condimentum. Etiam pretium turpis eget nibh laoreet iaculis. Vivamus auctor mi eget odio feugiat, quis aliquet velit ornare. Integer egestas sit amet neque sed elementum. </p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-3 col-sm-6">
					<div class="milestone-item text-white">
						<i class="flaticon-shared-folder"></i>
						<h2>24k</h2>
						<p>Clients</p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="milestone-item text-white">
						<i class="flaticon-social-media"></i>
						<h2>37k</h2>
						<p>Followers</p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="milestone-item text-white">
						<i class="flaticon-cloud-computing"></i>
						<h2>8k</h2>
						<p>Cloud users</p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="milestone-item text-white">
						<i class="flaticon-customer"></i>
						<h2>4k</h2>
						<p>Reviews</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Sčítání lidu END -->


	<!-- O týmu -->
	<section class="team-section spad">
		<div class="container">
			<div class="section-title">
				<img src="./img/section-title-icon.png" alt="#">
				<p>Banji</p>
				<h2>Náš tým</h2>
			</div>
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<div class="team-member">
						<img src="img/team/1.jpg" alt="#">
						<h4>Daniel Smith</h4>
						<p>Team manager</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="team-member">
						<img src="img/team/2.jpg" alt="#">
						<h4>Michael Joe</h4>
						<p>Developer</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="team-member">
						<img src="img/team/3.jpg" alt="#">
						<h4>Maria Williams</h4>
						<p>Designer</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="team-member">
						<img src="img/team/4.jpg" alt="#">
						<h4>Jane Doe</h4>
						<p>Maketing</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- O týmu END-->
