	<!-- Reset hesla-->
	<section class="contact-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 contact-text">
					<h4>Zapomnìli jste heslo?</h4>
					<p>V pøípadì, že jste zapomnìli Vaše heslo, zadejte svùj pøihlašovací email. Po odeslání Vám bude zaslán na e-mail kód pro obnovu hesla.</p>
				</div>
				<div class="col-lg-9">
					<form class="contact-form">
						<div class="row">
							<div class="col-md-6">
								<input type="text" placeholder="Zadejte svùj email">
							</div>
						    <div class="col-md-6">
								<button class="site-btn">Odeslat</button>
                            </div>
						</div>
					</form>
				</div>
               <div class="col-lg-4 contact-text">
					<h4></h4>
					<p>Pokud se vyskytnou komplikace pøi obnovì hesla, neváhejte se obrátit na našeho <a href="./contact.html">Administrátora</a>.</p>
				</div>
			</div>
		</div>
		<div class="map" id="map-canvas"></div>
	</section>
	<!-- Reset hesla END -->
