	<!-- Reset hesla-->
	<section class="contact-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 contact-text">
					<h4>Zapomněli jste heslo?</h4>
					<p>V případě, že jste zapomněli Vaše heslo, zadejte svůj přihlašovací email. Po odeslání Vám bude zaslán na e-mail kód pro obnovu hesla.</p>
				</div>
				<div class="col-lg-9">
					<form class="contact-form">
						<div class="row">
							<div class="col-md-6">
								<input type="text" placeholder="Zadejte svůj email">
							</div>
						    <div class="col-md-6">
								<button class="site-btn">Odeslat</button>
                                                    </div>
                                                    <div class="row">
                                                        <div>
                                                        <div class="g-recaptcha" data-sitekey="6LeAft0UAAAAAGXjGBx00xZgrPc34l_-zIuEYqOa"></div>
                                                        </div>    
                                                    </div>    
						</div>
					</form>
                                    <script src='https://www.google.com/recaptcha/api.js'></script>
				</div>
               <div class="col-lg-4 contact-text">
					<h4></h4>
					<p>Pokud se vyskytnou komplikace při obnově hesla, neváhejte se obrátit na našeho <a href="./contact.html">Administrátora</a>.</p>
				</div>
			</div>
		</div>
		<div class="spad"></div>
	</section>
	<!-- Reset hesla END -->
