<section class="contact-section">
    <div class="container">
        <div class="section-title">
            <img src="./img/section-title-icon.png" alt="#">
            <p>Banji</p>
            <h2>Přidat dítě</h2>
        </div>
    </div>
</section>
<section>
  <div class="container">
    <div class="row">
        <div class="col-4">
    </div>
    <div class="col-sm">
        <form class="contact-form" method="post">
        <div class="row">
    <div class="col-md-6">
    <label for="exampleInputName1">Kód dítěte:</label>
      <input type="text" class="form-control"  placeholder="Kód">
       <small id="kodHelp" class="form-text text-muted">Dodržujte velká a malá písmena.</small>
    </div>
    </div>
     
       
      
          
       
            <!-- Toto udělat lépe přes styly -->
            <div class="row">
                <div class="offset-sm-1">
                    <p></p>
                        
                      <a href="registrace-shrnuti" class="site-btn">Pokračovat</a>
                    <p></p>
                </div>
            </div>

        </form>
      
        <!-- Toto udělat lépe přes styly -->
        <div class="row"><p></p></div>
          
        <!-- Sekce s odkazy -->
   
        </div>
    </div>
  </div>
    <!-- Odsazení na konci stránky-->
    <div class="spad">  
    </div>
</section>

