<section class="contact-section">
    <div class="container">
        <div class="section-title">
            <img src="./img/section-title-icon.png" alt="#">
            <p>Banji</p>
            <h2>Přihlášení do portálu</h2>
        </div>
    </div>
</section>
<section>
  <div class="container">
    <div class="row">
        <div class="col-4">
    </div>
    <div class="col-sm">
        <form class="contact-form" method="post">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Vaše emailová adresa:</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="vas@email.com">
                        <small id="emailHelp" class="form-text text-muted">Nikomu nesděluj své přihlašovací údaje.</small>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="exampleInputPassword1">Vaše heslo:</label>
                        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Heslo">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <p>Nejsi robot?</p>
                        <div class="g-recaptcha" data-sitekey="6LeAft0UAAAAAGXjGBx00xZgrPc34l_-zIuEYqOa"></div>
                    </div>
                </div>
            </div>
            <!-- Toto udělat lépe přes styly -->
            <div class="row">
                <div class="offset-sm-1">
                    <p></p>
                        <button type="submit" class="site-btn">Odeslat</button>
                    <p></p>
                </div>
            </div>

        </form>
        <script src='https://www.google.com/recaptcha/api.js'></script>
        <!-- Toto udělat lépe přes styly -->
        <div class="row"><p></p></div>
          
        <!-- Sekce s odkazy -->
        <div class="row">
            <p>
                <a href="obnova-hesla">Zapomněl jsem svoje heslo.</a>
            </p>
        </div>
            <div class="row">
                <p>
                    <a href="registrace">Nemám ještě svůj účet.</a>
                </p>
            </div>
        </div>
    </div>
  </div>
    <!-- Odsazení na konci stránky-->
    <div class="spad">  
    </div>
</section>
