<section class="contact-section">
    <div class="container">
        <div class="section-title">
            <img src="./img/section-title-icon.png" alt="#">
            <p>Banji</p>
            <h2>Shrnutí registrace</h2>
        </div>
    </div>
</section>
<section>
  <div class="container">
    <div class="row">
        <div class="col-4">
    </div>
    <div class="col-sm">
        <form class="contact-form" method="post">
        <div class="row">
       <div class="col-4">
    <label for="staticName" class=>Jméno příjmení</label>
    </div>    
    </div>
      <div class="row">
         <div class="col-4">
   <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Údaje souhlasí.</label>
  </div>
    </div>    
    </div>
    
      <div class="row">
       <div class="col-4">
   <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Souhlasím s pravidly.</label>
  </div>
    </div>    
    </div>
     
       
      
          
       
            <!-- Toto udělat lépe přes styly -->
            <div class="row">
                <div class="offset-sm-1">
                    <p></p>
                        
                      <a href="./domu.html" class="site-btn">Registrovat</a>
                    <p></p>
                </div>
            </div>

        </form>
      
        <!-- Toto udělat lépe přes styly -->
        <div class="row"><p></p></div>
          
        <!-- Sekce s odkazy -->
   
        </div>
    </div>
  </div>
    <!-- Odsazení na konci stránky-->
    <div class="spad">  
    </div>
</section>

