<!-- školka 1 -->
	<section class="domain-search-section sc-about-page">
		<div class="container">
			<div class="section-title">
				<img src="./img/section-title-icon.png" alt="#">
				<p>Banji</p>
				<h2>Název školky 1</h2>
			</div>
		</div>
	</section>
	<!-- školka 1 END -->


	<!-- Školka 1 text-->
	<section class="about-section spad pt-0">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 about-text">
					<h3>Co děláme v projektu</h3>
					<p>Nullam lacinia ex eleifend orci porttitor, suscipit interdum augue condimentum. Etiam pretium turpis eget nibh laoreet iaculis. Vivamus auctor mi eget odio feugiat, quis aliquet velit ornare. Integer egestas sit amet neque sed elementum. Fusce ut turpis felis. Etiam pretium pharetra augue, ac porttitor dolor consequat eget. Cras tempor suscipit enim vehicula ultrices. Mauris sed orci blandit, rhoncus massa non, tincidunt odio. Ut ullamcorper lobortis hendrerit. </p>
				</div>
				<div class="col-lg-6">
					<img src="./img/about.jpg" alt="">
				</div>
			</div>
		</div>
	</section>
	<!-- Školka 1 END -->


	<!-- Bylo sčítání lidu -->
	<section class="milestones-section set-bg">
		<div class="container">
			<div class="row milestones-top-text">
			</div>
				<!-- školka 2 -->
	<section class="domain-search-section sc-about-page">
		<div class="container">
			<div class="section-title">
				<img src="./img/section-title-icon.png" alt="#">
				<p>Banji</p>
				<h2>Název školky 2</h2>
			</div>
		</div>
            </div>
                
	</section>
	<!-- školka 2 END -->


	<!-- Školka 2 text-->
	<section class="about-section spad pt-0">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 about-text">
					<h3>Co děláme v projektu</h3>
					<p>Nullam lacinia ex eleifend orci porttitor, suscipit interdum augue condimentum. Etiam pretium turpis eget nibh laoreet iaculis. Vivamus auctor mi eget odio feugiat, quis aliquet velit ornare. Integer egestas sit amet neque sed elementum. Fusce ut turpis felis. Etiam pretium pharetra augue, ac porttitor dolor consequat eget. Cras tempor suscipit enim vehicula ultrices. Mauris sed orci blandit, rhoncus massa non, tincidunt odio. Ut ullamcorper lobortis hendrerit. </p>
				</div>
				<div class="col-lg-6">
					<img src="./img/about.jpg" alt="">
				</div>
			</div>
		</div>
	</section>
	<!-- Školka 2 END -->
		</div>
	</section>
	<!-- Bylo sčítání lidu END -->


	<!-- Školka 3 -->
	<section class="team-section spad">
		<div class="container">
			<div class="section-title">
				<img src="./img/section-title-icon.png" alt="#">
				<p>Banji</p>
				<h2>Název školky 3</h2>
			</div>

		</div>
	</section>
	<!-- Školka 3 END-->

    <!-- Školka 3 text-->
	<section class="about-section spad pt-0">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 about-text">
					<h3>Co děláme v projektu</h3>
					<p>Nullam lacinia ex eleifend orci porttitor, suscipit interdum augue condimentum. Etiam pretium turpis eget nibh laoreet iaculis. Vivamus auctor mi eget odio feugiat, quis aliquet velit ornare. Integer egestas sit amet neque sed elementum. Fusce ut turpis felis. Etiam pretium pharetra augue, ac porttitor dolor consequat eget. Cras tempor suscipit enim vehicula ultrices. Mauris sed orci blandit, rhoncus massa non, tincidunt odio. Ut ullamcorper lobortis hendrerit. </p>
				</div>
				<div class="col-lg-6">
					<img src="./img/about.jpg" alt="">
				</div>
			</div>
		</div>
	</section>
	<!-- Školka 3 END -->
